#!/bin/bash

size="10"
if [ -n "$1" ]; then
  size="$1"
fi

while true; do
  files=`find . ! -executable -type f -size +"$size"k -name "*.cdata.bz2" |sort`
  if [ -z "$files" ]; then
    sleep 1
    echo -n .
    continue
  fi

  echo -e "\e[1;32m"
  ls -lh $files
  echo -e "\e[0m"

  f=`echo "$files" | head -n 1`

  cdp $f
  chmod u+x $f
done
